version: '3'

networks:
  default:
    driver: bridge

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user_teste
      POSTGRES_PASSWORD: S3cur3P4ssw0rd!
      POSTGRES_DB: postgres_teste
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/inicio.sql:/docker-entrypoint-initdb.d/inicio.sql
    networks:
      - default

  #app:
  #  build:
  #    context: ./app
  #    dockerfile: Dockerfile
  #  container_name: app
  #  volumes:
  #    - ./app:/clinica_pet
  #  depends_on:
  #    - postgres
  #  ports:
  #    - "8001:8000"
  #  restart: always
  #  networks:
  #    - default
#
  #produto_fisico:
  #  build:
  #    context: .
  #    dockerfile: produto_fisico/Dockerfile
  #  container_name: produto_fisico
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - redis
  #    - postgres
  #  restart: always
  #  environment:
  #    - PYTHONPATH=/app
  #    - DATABASE_URL=postgresql+psycopg2://user_teste:S3cur3P4ssw0rd!@postgres:5432/postgres_teste
  #    - ENV_FOR_DYNACONF=development
  #  networks:
  #    - default
#
  #processar_associacao:
  #  build:
  #    context: .
  #    dockerfile: processar_associacao/Dockerfile
  #  container_name: processar_associacao
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - redis
  #    - postgres
  #    - mailhog
  #  restart: always
  #  environment:
  #    - PYTHONPATH=/app
  #    - DATABASE_URL=postgresql+psycopg2://user_teste:S3cur3P4ssw0rd!@postgres:5432/postgres_teste
  #    - ENV_FOR_DYNACONF=development
  #    - MAILHOG_HOST=mailhog
  #  networks:
  #    - default
#
  #processar_streaming:
  #  build:
  #    context: .
  #    dockerfile: processar_streaming/Dockerfile
  #  container_name: processar_streaming
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - redis
  #    - postgres
  #    - mailhog
  #  restart: always
  #  environment:
  #    - PYTHONPATH=/app
  #    - DATABASE_URL=postgresql+psycopg2://user_teste:S3cur3P4ssw0rd!@postgres:5432/postgres_teste
  #    - ENV_FOR_DYNACONF=development
  #    - MAILHOG_HOST=mailhog
  #  networks:
  #    - default
#
  #processar_comissao:
  #  build:
  #    context: .
  #    dockerfile: processar_comissao/Dockerfile
  #  container_name: comissao
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - redis
  #    - postgres
  #  restart: always
  #  environment:
  #    - PYTHONPATH=/app
  #    - DATABASE_URL=postgresql+psycopg2://user_teste:S3cur3P4ssw0rd!@postgres:5432/postgres_teste
  #    - ENV_FOR_DYNACONF=development
  #  networks:
  #    - default
#
  #processar_guia_remessa:
  #  build:
  #    context: .
  #    dockerfile: processar_guia_remessa/Dockerfile
  #  container_name: guia_remessa
  #  volumes:
  #    - .:/app
  #  depends_on:
  #    - redis
  #    - postgres
  #  restart: always
  #  environment:
  #    - PYTHONPATH=/app
  #    - DATABASE_URL=postgresql+psycopg2://user_teste:S3cur3P4ssw0rd!@postgres:5432/postgres_teste
  #    - ENV_FOR_DYNACONF=development
  #  networks:
  #    - default  